#!/bin/bash
rm -r /var/lib/docker/volumes/docker-server_hue-stats/*
rm -r /var/lib/docker/volumes/docker-server_hue-demos/*
ln -s $(pwd)/docker-volumes/hue-stats/ /var/lib/docker/volumes/docker-server_hue-stats/_data
ln -s $(pwd)/docker-volumes/hue-demos/ /var/lib/docker/volumes/docker-server_hue-demos/_data

rm -r /var/lib/docker/volumes/docker-server_fone-stats/*
rm -r /var/lib/docker/volumes/docker-server_fone-demos/*
ln -s $(pwd)/docker-volumes/fone-stats/ /var/lib/docker/volumes/docker-server_fone-stats/_data
ln -s $(pwd)/docker-volumes/fone-demos/ /var/lib/docker/volumes/docker-server_fone-demos/_data

rm -r /var/lib/docker/volumes/docker-server_legacy-huetf-stats/*
rm -r /var/lib/docker/volumes/docker-server_legacy-huetf-demos/*
ln -s $(pwd)/docker-volumes/legacy-huetf-stats/ /var/lib/docker/volumes/docker-server_legacy-huetf-stats/_data
ln -s $(pwd)/docker-volumes/legacy-huetf-demos/ /var/lib/docker/volumes/docker-server_legacy-huetf-demos/_data

rm -r /var/lib/docker/volumes/docker-server_configs/*
ln -s $(pwd)/docker-volumes/configs/ /var/lib/docker/volumes/docker-server_configs/_data
