---
version: "3.7"
services:
  wtfapp-backend:
    image: qwtfbrasil/wtfapp-backend:latest
    restart: always
    ports:
      - "80:80"
  updater:
    image: qwtfbrasil/updater-arm64:latest
    restart: always
    environment:
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - S3_DEMO_URI
      - S3_STATS_URI
    volumes:
      - assets:/updater/map-repo/fortress/
      - master_dats:/updater/dats/master/
      - staging_dats:/updater/dats/staging/
      - fone-demos:/updater/demos/fo/
      - fone-stats:/updater/stats/fo/
      - hue-demos:/updater/demos/hue/
      - hue-stats:/updater/stats/hue/
      - legacy-huetf-demos:/updater/demos/legacy-huetf
      - legacy-huetf-stats:/updater/stats/legacy-huetf
    deploy:
      resources:
        limits:
          cpus: '0.10'
  00-hue:
    image: qwtfbrasil/fortressonesv-arm64:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27500
      +set hostname "${FO_HOSTNAME} Hue 00"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +serverinfo tfx 0
      +localinfo fologinrequired 0
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_quadmode.cfg
      +exec configs/huetf.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - hue-demos:/fortressonesv/fortress/demos/
      - hue-stats:/fortressonesv/fortress/data/
      - configs:/fortressonesv/fortress/configs/
  02-hue:
    image: qwtfbrasil/fortressonesv-arm64:latest
    depends_on:
      - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27502
      +set hostname "${FO_HOSTNAME} Hue 02"
      +serverinfo hostname "${FO_HOSTNAME} Hue 02"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +serverinfo tfx 0
      +localinfo fologinrequired 0
      +localinfo adminpwd "${FO_ADMINPWD}"
      +exec fo_quadmode.cfg
      +exec configs/huetf.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - hue-demos:/fortressonesv/fortress/demos/
      - hue-stats:/fortressonesv/fortress/data/
      - configs:/fortressonesv/fortress/configs/
  04-fo:
    image: qwtfbrasil/fortressonesv-arm64:latest
    depends_on:
     - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27504
      +set hostname "${FO_HOSTNAME} FOne 04"
      +serverinfo hostname "${FO_HOSTNAME} FOne 04"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo em 1
      +localinfo fologinrequired 0
      +exec fo_quadmode.cfg
      +exec configs/fone.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - fone-demos:/fortressonesv/fortress/demos/
      - fone-stats:/fortressonesv/fortress/data/
      - configs:/fortressonesv/fortress/configs/
  06-fo:
    image: qwtfbrasil/fortressonesv-arm64:latest
    depends_on:
     - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27506
      +set hostname "${FO_HOSTNAME} FOne 06"
      +serverinfo hostname "${FO_HOSTNAME} FOne 06"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +localinfo em 1
      +localinfo fologinrequired 0
      +exec fo_quadmode.cfg
      +exec configs/fone.cfg
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - master_dats:/fortressonesv/fortress/dats/
      - fone-demos:/fortressonesv/fortress/demos/
      - fone-stats:/fortressonesv/fortress/data/
      - configs:/fortressonesv/fortress/configs/
  08-practice:
    image: qwtfbrasil/fortressonesv-arm64:latest
    depends_on:
     - updater
    stdin_open: true
    tty: true
    restart: always
    command: |
      -ip ${FO_IP}
      -port 27508
      +set hostname "${FO_HOSTNAME} Practice 08"
      +serverinfo hostname "${FO_HOSTNAME} Practice 08"
      +set password "${FO_PASSWORD}"
      +set rcon_password "${FO_RCON_PASSWORD}"
      +localinfo adminpwd "${FO_ADMINPWD}"
      +serverinfo tfx 0
      +localinfo forequirelogin 0
      +exec fo_quadmode.cfg
      +exec configs/fone.cfg
      +set sv_cheats 1
      +localinfo max_gren2_medic 999
      +localinfo max_gren1_medic 999
      +localinfo max_gren1_soldier 999
      +localinfo max_gren2_soldier 999
      +localinfo max_gren1_demoman 999
      +localinfo max_gren2_demoman 999
      +localinfo max_gren1_engineer 999
      +localinfo max_gren2_engineer 999
      +localinfo max_gren1_pyro 999
      +localinfo max_gren2_pyro 999
      +localinfo max_gren2_scout 999
      +localinfo round_time 30
      +map 2fort5r
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - staging_dats:/fortressonesv/fortress/dats/
      - configs:/fortressonesv/fortress/configs/
  10-legacy-huetf:
    image: qwtfbrasil/huetflegacy-arm64:latest
    stdin_open: true
    tty: true
    restart: always
    command: |
      -game fortress
      -nohome
      -ip ${FO_IP}
      -port 27510
      +set hostname "#Sao Januario, Meu Caldeirao Legacy HueTF 10"
      +serverinfo hostname "#Sao Januario, Meu Caldeirao Legacy HueTF 10"
      +exec public.cfg
      +map wellgl1
    network_mode: "host"
    volumes:
      - assets:/fortressonesv/fortress/assets/
      - legacy-huetf-demos:/fortressonesv/fortress/demos/
      - legacy-huetf-stats:/fortressonesv/fortress/data/
  qwfwd:
    image: qwtfbrasil/qwfwd-arm64:latest
    network_mode: "host"
    stdin_open: true
    tty: true
    restart: always
    command: |
      30000 0.0.0.0
      +set hostname "${FO_HOSTNAME} QWfwd"
volumes:
  assets:
  master_dats:
  staging_dats:
  fone-demos:
  fone-stats:
  hue-demos:
  hue-stats:
  configs:
  hue_dats:
  legacy-huetf-demos:
  legacy-huetf-stats:
